name: codestyle

on:
  pull_request:
    branches:
      - master

jobs:
  codestyle:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          pip install black==23.3.0
          pip install isort

      - name: Lint with flake8
        run: python -m flake8

      - name: Codestyle by black
        run: black . --diff

      - name: Codestyle by isort
        run: isort . --diff
